config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  get 'notifications/index'

  resources :configurations
  resources :projects
  resources :commits
  resources :rules
  resources :rule_sets
  resources :notifications

  namespace :api, path: '', constraints: { subdomain: 'api' }, defaults: { format: :json } do
    namespace :v1 do
      resources :configurations
      resources :projects
      resources :commits do
        collection do
          get 'wipe'
        end
      end
      resources :rules
      resources :rule_sets
    end
  end

  get 'dashboard/index'
  get 'configurations/index'
  get 'projects/index'
  get 'commits/index'
  get 'rules/index'
  get 'rule_sets/index'
  get 'notifications/index'

  mount Sidekiq::Web => '/sidekiq'

  root 'dashboard#index'
end

app/models/configurations.rb
=begin
Copyright 2016 SourceClear Inc

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
=end

class Configurations < Sequel::Model
end

app/controllers/api/v1/configurations_controller.rb
=begin
Copyright 2016 SourceClear Inc

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
=end

class API::V1::ConfigurationsController < ApplicationController
  def index
    @configurations = Configurations
    render json: @configurations
  end

  def update
    @configuration = Configurations[id: params[:id].to_i]
    begin
      @configuration.update(configuration_params)
      render json: { status: 'ok', message: 'configuration updated' }
    rescue Sequel::ValidationFailed, Sequel::DatabaseError => e
      render json: { status: 'error', message: e }
    end
  end

private

  def configuration_params
    params.require(:name)
    params.require(:audit_frequency)
    params.require(:github_token)
    params.permit(:name, :audit_frequency, :github_token)
  end
end

app/controllers/configurations_controller.rb
=begin
Copyright 2016 SourceClear Inc

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
=end

class ConfigurationsController < ApplicationController
  def index
    @configurations = Configurations
  end

  def edit
    @configuration = Configurations[id: params[:id].to_i]
  end

  def update
    @configuration = Configurations[id: params[:id].to_i]
    begin
      @configuration.update(configuration_params)
      redirect_to action: 'index'
    rescue Sequel::ValidationFailed
      render 'edit'
    rescue Sequel::DatabaseError => e
      render 'edit'
    end
  end

private

  def configuration_params
    params.require(:configuration).permit(:name, :audit_frequency, :github_token)
  end
end

app/helpers/configurations_helper.rb
=begin
Copyright 2016 SourceClear Inc

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
=end

module ConfigurationsHelper
end

app/views/configurations/edit.html.erb
<% if false %>
Copyright 2016 SourceClear Inc

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
<% end %>

<h1>Editing Configuration</h1>

<%= form_for :configuration, url: configuration_path(@configuration.id), method: :patch do |f| %>

  <% if @configuration.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@configuration.errors.count, "error") %> prohibited
        this configuration from being saved:
      </h2>
      <ul>
        <% @configuration.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :audit_frequency %><br>
    <%= f.text_field :audit_frequency %>
  </p>

  <p>
    <%= f.label :github_token %><br>
    <%= f.text_field :github_token %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

<%= link_to 'Back', configurations_path %>

app/views/configurations/index.html.erb
<% if false %>
Copyright 2016 SourceClear Inc

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
<% end %>

<h1>Configurations</h1>

<p><%= link_to 'Dashboard', controller: 'dashboard' %></p>

<table border="1" cellpadding="10">
  <tr>
    <th>Name</th>
    <th>Audit Frequency</th>
    <th>GitHub Token</th>
    <th></th>
  </tr>

  <% @configurations.each do |configuration| %>
    <tr>
      <td><%= configuration.name %></td>
      <td><%= configuration.audit_frequency %></td>
      <td><%= configuration.github_token %></td>
      <td><%= link_to 'Edit', edit_configuration_path(configuration.id) %></td>
    </tr>
  <% end %>
</table>