config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  get 'notifications/index'

  resources :configurations
  resources :projects
  resources :commits
  resources :rules
  resources :rule_sets
  resources :notifications

  namespace :api, path: '', constraints: { subdomain: 'api' }, defaults: { format: :json } do
    namespace :v1 do
      resources :configurations
      resources :projects
      resources :commits do
        collection do
          get 'wipe'
        end
      end
      resources :rules
      resources :rule_sets
    end
  end

  get 'dashboard/index'
  get 'configurations/index'
  get 'projects/index'
  get 'commits/index'
  get 'rules/index'
  get 'rule_sets/index'
  get 'notifications/index'

  mount Sidekiq::Web => '/sidekiq'

  root 'dashboard#index'
end

app/models/notifications.rb
=begin
Copyright 2016 SourceClear Inc

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
=end

class Notifications < Sequel::Model
  plugin :validation_helpers

  def validate
    super

    validates_presence [:name, :notification_type_id, :target]
    validates_includes NotificationTypes.keys, :notification_type_id
  end
end

app/controllers/notifications_controller.rb
=begin
Copyright 2016 SourceClear Inc

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
=end

class NotificationsController < ApplicationController
  def index
    @notifications = Notifications
  end

  def edit
    @notification = Notifications[id: params[:id].to_i]
  end

  def create
    @notification = Notifications.new(notification_params)
    begin
      @notification.save
      redirect_to action: 'index'
    rescue Sequel::ValidationFailed
      render 'new'
    rescue Sequel::DatabaseError => e
      render 'new'
    end
  end

  def update
    @notification = Notifications[id: params[:id].to_i]
    begin
      @notification.update(notification_params)
      redirect_to action: 'index'
    rescue Sequel::ValidationFailed
      render 'edit'
    rescue Sequel::DatabaseError => e
      render 'edit'
    end
  end

  def destroy
    @notification = notifications[id: params[:id].to_i]
    @notification.destroy

    redirect_to notifications_path
  end

private

  def notification_params
    params.require(:notification).permit(:name, :notification_type_id, :target)
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/edit.html.erb
<% if false %>
Copyright 2016 SourceClear Inc

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
<% end %>

<h1>Editing Notification</h1>

<%= form_for :notification, url: notification_path(@notification.id), method: :patch do |f| %>

  <% if @notification.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@notification.errors.count, 'error') %> prohibited
        this notification from being saved:
      </h2>
      <ul>
        <% @notification.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :notification_type_id %><br>
    <%= f.select :notification_type_id, NotificationTypes.collect { |k, v| [v[:name], k] } %>
  </p>

  <p>
    <%= f.label :target %><br>
    <%= f.text_field :target %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

<%= link_to 'Back', notifications_path %>

app/views/notifications/index.html.erb
<% if false %>
Copyright 2016 SourceClear Inc

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
<% end %>

<h1>Notifications</h1>

<p><%= link_to 'Dashboard', controller: 'dashboard' %></p>

<%= link_to 'New Notification', new_notification_path %>
<table border="1" cellpadding="10">
  <tr>
    <th>Name</th>
    <th>Notification Type</th>
    <th>Target</th>
    <th colspan="2"></th>
  </tr>

  <% @notifications.each do |notification| %>
    <tr>
      <td><%= notification.name %></td>
      <td><%= "#{NotificationTypes[notification.notification_type_id][:name]} (#{notification.notification_type_id})" %></td>
      <td><%= notification.target %></td>
      <td><%= link_to 'Edit', edit_notification_path(notification.id) %></td>
      <td><%= link_to 'Delete', notification_path(notification.id),
        method: :delete,
        data: { confirm: 'Really? Are you being serious right now?' } %></td>
    </tr>
  <% end %>
</table>

app/views/notifications/new.html.erb
<% if false %>
Copyright 2016 SourceClear Inc

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
<% end %>

<h1>New Notification</h1>

<%= link_to 'Back', notifications_path %>

<%= form_for :notification, url: notifications_path do |f| %>

  <% if @notification && @notification.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@notification.errors.count, 'error') %> prohibited
        this notification from being created:
      </h2>
      <ul>
        <% @notification.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :notification_type_id %><br>
    <%= f.select :notification_type_id, NotificationTypes.collect { |k, v| [v[:name], k] } %>
  </p>

  <p>
    <%= f.label :target %><br>
    <%= f.text_field :target %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>