config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  get 'notifications/index'

  resources :configurations
  resources :projects
  resources :commits
  resources :rules
  resources :rule_sets
  resources :notifications

  namespace :api, path: '', constraints: { subdomain: 'api' }, defaults: { format: :json } do
    namespace :v1 do
      resources :configurations
      resources :projects
      resources :commits do
        collection do
          get 'wipe'
        end
      end
      resources :rules
      resources :rule_sets
    end
  end

  get 'dashboard/index'
  get 'configurations/index'
  get 'projects/index'
  get 'commits/index'
  get 'rules/index'
  get 'rule_sets/index'
  get 'notifications/index'

  mount Sidekiq::Web => '/sidekiq'

  root 'dashboard#index'
end

app/models/projects.rb
=begin
Copyright 2016 SourceClear Inc

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
=end

require 'json'

class Projects < Sequel::Model
  plugin :validation_helpers

  def validate
    super

    validates_presence [:name, :rule_sets]
    validates_unique :name
    validates_format %r|\A[a-z\d][\w\-]{0,38}/[\w\-]{0,60}|i, :name
    validates_min_length 3, :name, message: -> (s) { "of project must be more than #{s} characters" }

    begin
        rule_set_names = JSON.parse(rule_sets)

        # Allow projects to be 'disabled' by emptying rule sets
        #errors.add(:rule_sets, 'must include at least one rule set') if rule_set_names.empty?

        all_sets_names = RuleSets.select(:name).collect { |r| r[:name] }
        rule_set_names.each do |set_name|
            next if all_sets_names.include?(set_name)
            errors.add(:rule_sets, "referenced rule set does not exist: #{set_name}")
        end
    rescue JSON::ParserError => e
        errors.add(:rule_sets, "invalid JSON value: #{rule_sets} - #{e}")
    end
  end
end

app/controllers/api/v1/projects_controller.rb
=begin
Copyright 2016 SourceClear Inc

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
=end

class API::V1::ProjectsController < ApplicationController
  protect_from_forgery with: :null_session

  def index
    @projects = Projects
    render json: @projects
  end

  def show
    @project = Projects[id: params[:id].to_i]
    render json: @project
  end

  def create
    @project = Projects.new(create_project_params)
    begin
      @project.save
      render json: { status: 'ok', message: 'project created' }
    rescue Sequel::ValidationFailed, Sequel::DatabaseError => e
      render json: { status: 'error', message: e }
    end
  end

  def update
    @project = Projects[id: params[:id].to_i]
    begin
      @project.update(update_project_params)
      render json: { status: 'ok', message: 'project updated' }
    rescue Sequel::ValidationFailed, Sequel::DatabaseError => e
      render json: { status: 'error', message: e }
    end
  end

  def destroy
    @project = Projects[id: params[:id].to_i]
    @project.destroy
    render json: { status: 'ok', message: 'project destroyed' }
  end

private

  def create_project_params
    params.require(:name)
    params.require(:rule_sets)
    params.permit(:name, :rule_sets)
  end

  def update_project_params
    params.require(:name)
    params.require(:rule_sets)
    params.require(:next_audit)
    params.require(:last_commit_time)
    params.permit(:name, :rule_sets, :next_audit, :last_commit_time)
  end
end

app/controllers/projects_controller.rb
=begin
Copyright 2016 SourceClear Inc

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
=end

require_relative "#{Rails.root}/lib/github_api"

class ProjectsController < ApplicationController
  def index
    page = params[:page] ? params[:page].to_i : 1
    results_per_page = 100
    @projects = Projects.select_all(:projects)
    @projects = @projects.paginate(page, results_per_page)
  end

  def edit
    @project = Projects[id: params[:id].to_i]
  end

  def create
    params = create_project_params
    begin
      if params[:name].include?('/')
        @project = import_project(params[:name], params[:rule_sets], params[:username], params[:access_token])
      else
        @project = import_user(params[:name], params[:rule_sets], params[:username], params[:access_token])
      end

      redirect_to action: 'index'
    rescue Sequel::ValidationFailed
      render 'new'
    rescue Sequel::DatabaseError => e
      render 'new'
    end
  end

  def update
    @project = Projects[id: params[:id].to_i]
    begin
      @project.update(update_project_params)
      redirect_to action: 'index'
    rescue Sequel::ValidationFailed
      render 'edit'
    rescue Sequel::DatabaseError => e
      render 'edit'
    end
  end

  def destroy
    @project = Projects[id: params[:id].to_i]
    @project.destroy

    redirect_to projects_path
  end

private

  def import_user(name, rule_sets, username, access_token)
    github_token = Configurations.first.github_token
    gh = GitHubAPI.new(github_token)
    repo_names = gh.get_repo_names(name)
    repo_names.each do |repo_name|
      import_project("#{name}/#{repo_name}", rule_sets, username, access_token)
    end
  end

  def import_project(name, rule_sets, username, access_token)
    project = Projects.new({ name: name, rule_sets: rule_sets, username: username, access_token: access_token })
    project.save
    project
  end

  def create_project_params
    params.require(:project).permit(:name, :rule_sets, :username, :access_token)
  end

  def update_project_params
    params.require(:project).permit(:name, :rule_sets, :username, :access_token, :next_audit, :last_commit_time)
  end
end

app/helpers/projects_helper.rb
=begin
Copyright 2016 SourceClear Inc

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
=end

module ProjectsHelper
end

app/views/projects/edit.html.erb
<% if false %>
Copyright 2016 SourceClear Inc

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
<% end %>

<h1>Editing Project</h1>

<%= form_for :project, url: project_path(@project.id), method: :patch do |f| %>

  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@project.errors.count, 'error') %> prohibited
        this project from being saved:
      </h2>
      <ul>
        <% @project.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </p>

  <p>
    <%= f.label :access_token %><br>
    <%= f.text_field :access_token %>
  </p>

  <p>
    <%= f.label :rule_sets %><br>
    <%= f.text_field :rule_sets %>
  </p>

  <p>
    <%= f.label :next_audit %><br>
    <%= f.text_field :next_audit %>
  </p>

  <p>
    <%= f.label :last_commit_time %><br>
    <%= f.text_field :last_commit_time %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<% if false %>
Copyright 2016 SourceClear Inc

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
<% end %>

<h1>Projects</h1>

<p><%= link_to 'Dashboard', controller: 'dashboard' %></p>

<%= link_to 'New Project', new_project_path %>
<table border="1" cellpadding="10">
  <tr>
    <th>Id</th>
    <th>Name</th>
    <th>Rule Sets</th>
    <th>Next Audit</th>
    <th>Last Commit Time</th>
    <th>Date Created</th>
    <th colspan="2"></th>
  </tr>

  <% @projects.each do |project| %>
    <tr>
      <td><%= project.id %></td>
      <td><%= project.name %></td>
      <td><%= project.rule_sets %></td>
      <td><%= project.next_audit %></td>
      <td><%= project.last_commit_time %></td>
      <td><%= project.date_created %></td>
      <td><%= link_to 'Edit', edit_project_path(project.id) %></td>
      <td><%= link_to 'Delete', project_path(project.id),
        method: :delete,
        data: { confirm: 'Really? Are you being serious right now?' } %></td>
    </tr>
  <% end %>
</table>

<%= paginate @projects %>

app/views/projects/new.html.erb
<% if false %>
Copyright 2016 SourceClear Inc

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
<% end %>

<h1>New Project</h1>

<%= link_to 'Back', projects_path %>

<%= form_for :project, url: projects_path do |f| %>

  <% if @project && @project.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@project.errors.count, 'error') %> prohibited
        this project from being saved:
      </h2>
      <ul>
        <% @project.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
  Using a group or username will cause all repositories of that name to be imported from GitHub.
  </p>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </p>

  <p>
    <%= f.label :access_token %><br>
    <%= f.text_field :access_token %>
  </p>

  <p>
    <%= f.label :rule_sets %><br>
    <%= f.text_area :rule_sets %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>