config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  get 'notifications/index'

  resources :configurations
  resources :projects
  resources :commits
  resources :rules
  resources :rule_sets
  resources :notifications

  namespace :api, path: '', constraints: { subdomain: 'api' }, defaults: { format: :json } do
    namespace :v1 do
      resources :configurations
      resources :projects
      resources :commits do
        collection do
          get 'wipe'
        end
      end
      resources :rules
      resources :rule_sets
    end
  end

  get 'dashboard/index'
  get 'configurations/index'
  get 'projects/index'
  get 'commits/index'
  get 'rules/index'
  get 'rule_sets/index'
  get 'notifications/index'

  mount Sidekiq::Web => '/sidekiq'

  root 'dashboard#index'
end

app/models/rule_sets.rb
=begin
Copyright 2016 SourceClear Inc

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
=end

require 'json'

class RuleSets < Sequel::Model
  plugin :validation_helpers

  def validate
    super

    validates_presence [:name, :rules]
    validates_unique :name
    validates_min_length 3, :name, message: -> (s) { "of rule set must be more than #{s} characters" }

    begin
        rule_names = JSON.parse(rules)
        errors.add(:rules, 'must include at least one rule') if rule_names.empty?

        all_rule_names = Rules.select(:name).collect { |r| r[:name] }
        rule_names.each do |rule_name|
            next if all_rule_names.include?(rule_name)
            errors.add(:rules, "referenced rule does not exist: #{rule_name}")
        end
    rescue JSON::ParserError => e
        errors.add(:rules, "invalid JSON value: #{rules} - #{e}")
    end
  end
end

app/controllers/api/v1/rule_sets_controller.rb
=begin
Copyright 2016 SourceClear Inc

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
=end

class API::V1::RuleSetsController < ApplicationController
  def index
    @rule_sets = RuleSets
    render json: @rule_sets
  end

  def show
    @rule_set = RuleSets[id: params[:id].to_i]
    render json: @rule_set
  end

  def create
    @rule_set = RuleSets.new(rule_set_params)
    begin
      @rule_set.save
      render json: { status: 'ok', message: 'rule set created' }
    rescue Sequel::ValidationFailed, Sequel::DatabaseError => e
      render json: { status: 'error', message: e }
    end
  end

  def update
    @rule_set = RuleSets[id: params[:id].to_i]
    begin
      @rule_set.update(rule_set_params)
      render json: { status: 'ok', message: 'rule set updated' }
    rescue Sequel::ValidationFailed, Sequel::DatabaseError => e
      render json: { status: 'error', message: e }
   end
  end

  def destroy
    @rule_set = RuleSets[id: params[:id].to_i]
    @rule_set.destroy
    render json: { status: 'ok', message: 'rule set destroyed' }
  end

private

  def rule_set_params
    params.require(:name)
    params.require(:rules)
    params.require(:description)
    params.permit(:name, :rules, :description)
  end
end

app/controllers/rule_sets_controller.rb
=begin
Copyright 2016 SourceClear Inc

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
=end

class RuleSetsController < ApplicationController
  def index
    @rule_sets = RuleSets
  end

  def edit
    @rule_set = RuleSets[id: params[:id].to_i]
  end

  def create
    @rule_set = RuleSets.new(rule_set_params)
    begin
      @rule_set.save
      redirect_to action: 'index'
    rescue Sequel::ValidationFailed
      render 'new'
    rescue Sequel::DatabaseError => e
      render 'new'
    end
  end

  def update
    @rule_set = RuleSets[id: params[:id].to_i]
    begin
      @rule_set.update(rule_set_params)
      redirect_to action: 'index'
    rescue Sequel::ValidationFailed
      render 'edit'
     rescue Sequel::DatabaseError => e
      render 'edit'
   end
  end

  def destroy
    @rule_set = RuleSets[id: params[:id].to_i]
    @rule_set.destroy

    redirect_to rule_sets_path
  end

private

  def rule_set_params
    params.require(:rule_set).permit(:name, :rules, :description)
  end
end

app/helpers/rule_sets_helper.rb
=begin
Copyright 2016 SourceClear Inc

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
=end

module RuleSetsHelper
end

app/views/rule_sets/edit.html.erb
<% if false %>
Copyright 2016 SourceClear Inc

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
<% end %>

<h1>Editing Rule Set</h1>

<%= form_for :rule_set, url: rule_set_path(@rule_set.id), method: :patch do |f| %>

  <% if @rule_set.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@rule_set.errors.count, 'error') %> prohibited
        this rule set from being saved:
      </h2>
      <ul>
        <% @rule_set.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :rules %><br>
    <%= f.text_field :rules %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

<%= link_to 'Back', rule_sets_path %>

app/views/rule_sets/index.html.erb
<% if false %>
Copyright 2016 SourceClear Inc

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
<% end %>

<h1>Rule Sets</h1>

<p><%= link_to 'Dashboard', controller: 'dashboard' %></p>

<%= link_to 'New Rule Set', new_rule_set_path %>
<table border="1" cellpadding="10">
  <tr>
    <th>Name</th>
    <th>Rules</th>
    <th>Description</th>
    <th colspan="2"></th>
  </tr>

  <% @rule_sets.each do |rule_set| %>
    <tr>
      <td><%= rule_set.name %></td>
      <td><%= rule_set.rules %></td>
      <td><%= rule_set.description %></td>
      <td><%= link_to 'Edit', edit_rule_set_path(rule_set.id) %></td>
      <td><%= link_to 'Delete', rule_set_path(rule_set.id),
        method: :delete,
        data: { confirm: 'Really? Are you being serious right now?' } %></td>
    </tr>
  <% end %>
</table>

app/views/rule_sets/new.html.erb
<% if false %>
Copyright 2016 SourceClear Inc

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
<% end %>

<h1>New Rule Set</h1>

<%= link_to 'Back', rule_sets_path %>

<%= form_for :rule_set, url: rule_sets_path do |f| %>

  <% if @rule_set && @rule_set.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@rule_set.errors.count, 'error') %> prohibited
        this rule set from being created:
      </h2>
      <ul>
        <% @rule_set.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :rules %><br>
    <%= f.text_field :rules %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>